### ISSUE TITLE
Polymer2

### ISSUE THREAD

**Issue by shersher** [lastmjs/redux-store-element#25]
are you planning to support Polymer2?

**Comment by lastmjs** [comment]
Yes I am, once it has a stable release. Are you using Polymer 2 already?

**Comment by shersher** [comment]
It is our October project.

**Comment by shersher** [comment]
I’m sure there will be much discussion at Polymer Summit, October 17 - 18, 2016 in London.

**Comment by lastmjs** [comment]
How soon into October would you need this? Are you going to be waiting until after the Polymer Summit? Like I said I would like to wait for a stable release, but if you really need it earlier I could probably do that.

**Comment by shersher** [comment]
Let me keep you posted.  The consensus here is to wait until after the Summit.  We will be watching the online stuff and I’ll schedule to check in with you after that.

Thanks,

Sher

**Comment by lastmjs** [comment]
This custom element is going Vanilla JS, so there will be no more Polymer dependency.
