### ISSUE TITLE
On every action a "@@redux/INIT" action type is also triggered

### ISSUE THREAD

**Issue by electrovir** [lastmjs/redux-store-element#29]
I caught this by using the following in my reducer:

```javascript
  switch(action.type) {
    default: {
      console.warn('uncaught action', action);
      return state;
    }
  }
```

This causes anything listening to the state change to trigger twice every time a single action is performed.

**Comment by lastmjs** [comment]
> This causes anything listening to the state change to trigger twice every time a single action is performed.

Are you saying that you think you found the cause?

**Comment by lastmjs** [comment]
Nevermind, I get what you're saying. This bug is causing state change listeners to be called twice for every action. I think I know what's happening, it was part of some unfinished work that I pushed up and have since rethought.
