### ISSUE TITLE
Example Unit Testing / Mocking

### ISSUE THREAD

**Issue by bradrydzewski** [lastmjs/redux-store-element#38]
I am sorry if this seems out of scope or the answer is obvious (I am new to webcomponents) but was wondering if there is a recommended approach to mocking / unit testing with a polymer application? If so would you be willing to include more details in the readme?

**Comment by lastmjs** [comment]
I believe Polymer would recommend to you their web component test runner: https://github.com/Polymer/web-component-tester

Personally, I'm going with my own solution: https://github.com/lastmjs/guesswork

My solution is working well for me, you can try it if you want, but it isn't well documented. I've found Polymer's tools beyond the Polymer library itself to be more complicated than I would like, and I believe there are simpler solutions. But they may work well for you.

**Comment by lastmjs** [comment]
And you can check out my testing structure in the test directory of this repository, it's probably similar in structure to what you'll find with the Polymer test runner, just so you can get an idea of testing using web components.

**Comment by bradrydzewski** [comment]
thanks for the reply!

so let's say (hypothetically) I am using an app router and have a bunch of different pages in my application, and each page uses the default redux store.

```
<redux-store id="redux-store-element"></redux-store>
```

if I want to unit test each page individually do I need to reset the store after each unit test so that I'm starting with a fresh state? Or am I thinking about this incorrectly? Again sorry for the noob questions and really appreciate your time!

**Comment by lastmjs** [comment]
Yes, that sounds correct to me. You don't want previous state sneeking up on you in future tests, so as much as possible each test should be self-contained. One way to do this would be to create a `RESET_STATE` reducer that returns the initial state, then you can fire that action in your tests and reset the state at any time.

**Comment by lastmjs** [comment]
Assuming you import the redux-store-element once for all of your tests cases, as in you don't refresh the page or do something else to load the redux-store-element's definition again. Once its loaded and the root reducer is set, that store will exist throughout the application's lifetime.

**Comment by lastmjs** [comment]
Contact me on Twitter or email me if you have any more questions, I'm happy to help.

**Comment by bradrydzewski** [comment]
thanks for the tips, much appreciated!
