### ISSUE TITLE
missing redux.min.js

### ISSUE THREAD

**Issue by chisholmd** [lastmjs/redux-store-element#43]
the redux-store.html is trying to load this:
<script src="../redux/dist/redux.min.js"></script>

But in the bower directory there is no such file

**Comment by lastmjs** [comment]
The element should be installed from npm now. If you want to use Bower, you'll have to use an older version of the element

**Comment by chisholmd** [comment]
Thanks.

**Comment by chisholmd** [comment]
I guess this means I need to have node installed in the project directory.
