### ISSUE TITLE
stores[this._storeName] = undefined

### ISSUE THREAD

**Issue by chisholmd** [lastmjs/redux-store-element#44]
Getting an error here:  
        set action(val) {
            stores[this._storeName].store.dispatch(val);
        }

When I set a break point and inspect in the console "stores" is {} and stores["DEFAULT_STORE"] is undefined.

Successf ully using this element in a Poly v1 app and now trying to set up a Polymer v2 app.  Might be related?

**Comment by lastmjs** [comment]
Make sure you set the root reducer before you fire any actions. Looks like your root reducer has not been set by the time you are firing the action, so the store has not been created

**Comment by chisholmd** [comment]
I have this in my <app> element
<redux-store root-reducer="[[rootReducer]]" ></redux-store>
  
A child element loaded via the router has
<redux-store action="[[action]]"></redux-store>

this.action = {type: 'TEST_ACTION',snee: "foo"}

**Comment by lastmjs** [comment]
Do you import and set the rootReducer in your app element? What does the JavaScript look like?

**Comment by chisholmd** [comment]
First, thanks so much for helping me.
In my index.html I import an elements file
 < link rel="import" href="/src/elements.html" >
and in the body of my index.html I have my app element.

In my elements files I import my app element and the redux-store-element in this order (is this order dependent?)

< link rel="import" href="/src/poly2app-app/poly2app-app.html" >
< link rel="import" href="/node_modules/redux-store-element/redux-store.html" >

In my app element I have
< redux-store root-reducer="[[rootReducer]]" on-statechange="_mapState"  >< /redux-store >
< redux-store action="[[action]]"  >< /redux-store >

 this.rootReducer = function(state, action) {
              if (!state) {
                  return initialState;
              }
              switch(action.type) {
                  case 'TEST_ACTION': {
                    var newState = Object.assign({}, state);
                    newState.test = true;                   
                    return newState;
                  }
                  default: {
                      return state;
                  }
              };
          };
          this.action = {type: 'DEFAULT_ACTION'};
      }

In a child element I have:
< redux-store action="[[action]]" >< /redux-store >

And I am firing the action via a paper-button for testing so it is well after everything is loaded:

this.$.dothis.addEventListener("click", function(){
          if(this.someId!=undefined){
             this.set('prop1', this.someId);
             this.action = {type: 'TEST_ACTION',snee: "foo"}
          }  
        }.bind(this))

**Comment by chisholmd** [comment]
With the imports loading in this order the "set rootReducer(val)" never gets called.

< link rel="import" href="/src/poly2app-app/poly2app-app.html" >
< link rel="import" href="/node_modules/redux-store-element/redux-store.html" >

If I switch the order then the "set rootReducer(val)" 
< link rel="import" href="/node_modules/redux-store-element/redux-store.html" >
< link rel="import" href="/src/poly2app-app/poly2app-app.html" >

However, as I step through the code the constructor gets called again which resets the _rootReducer to null.  What would cause the constructor to be called again?  Importing the redux-store.html twice?

**Comment by chisholmd** [comment]
Oh for crying out loud.... I was missing this:
                var initialState = {
                    temp: 'initial temp'
                };

Which caused the weird cascade of issues.

**Comment by lastmjs** [comment]
Glad to hear it. By the way, if I were you I would not load all elements from a single file, it makes each element less modular. Each element should directly load its own dependencies: https://github.com/webcomponents/gold-standard/wiki#loading

**Comment by electrovir** [comment]
I had this same problem but my cause was different. I could fire an action from the element that created the rootReducer but child elements that fired actions would throw this error.

I'm using Polymer 2 and setting ``this.rootReducer`` to a function from another script file (because the reducer is quite long). Initially I was doing this assignment in ``connectedCallback`` but once I moved it to ``constructor`` then it worked.

## Correct Way
```html
<dom-module id="my-component">
  <template>
    <redux-store action="[[action]]" root-reducer="[[rootReducer]]"></redux-store>
    <my-child-element></my-child-element>
  </template>
  
  <script>
    class MyComponentClass extends Polymer.Element {
      static get is() {
        return 'my-component';
      }
      
      constructor() {
        super();
        this.rootReducer = virAppReducer;
      }
      
      connectedCallback() {
        super.connectedCallback();
        this.action = {type: 'test action'};
      }  
    }

    customElements.define(MyComponentClass.is, MyComponentClass);
  </script>
</dom-module>
```

## Wrong Way
```html
<dom-module id="my-component">
  <template>
    <redux-store action="[[action]]" root-reducer="[[rootReducer]]"></redux-store>
    <my-child-element></my-child-element>
  </template>
  
  <script>
    class MyComponentClass extends Polymer.Element {
      static get is() {
        return 'my-component';
      }
      
      connectedCallback() {
        super.connectedCallback();
        this.rootReducer = virAppReducer;
        // this action will succeed but actions fired by child elements will fail
        this.action = {type: 'test action'};
      }  
    }

    customElements.define(MyComponentClass.is, MyComponentClass);
  </script>
</dom-module>
```
