### ISSUE TITLE
Usability feedback for action attribute when re-rendering

### ISSUE THREAD

**Issue by ernsheong** [lastmjs/redux-store-element#48]
The `action` attribute presumably tries to replace the imperative `dispatch` method in redux pattern, but in cases like lit-html where you just re-render the element, `action` is already set to the previous action, and creating a new `<redux-store-element action=${action}>` causes previous action to retrigger on a re-render.

Not quite a bug, but quite a blocker in the case of `lit-html` from my perspective, and requires work-around e.g. grabbing the redux element directly and setting action on it instead

**Comment by lastmjs** [comment]
I'll look into this, thanks for the feedback. Let me know of any suggestions you have for how the API should change

**Comment by lastmjs** [comment]
Perhaps the simplest thing for redux-store-element to do is implement its own change detection when the action property is set. Probably a reference check would be sufficient so that we don't have to do a deep equality check, and to encourage immutability.

**Comment by lastmjs** [comment]
Try the latest version, each property (rootReducer, storeName, and action) now has change detection based on reference equality. The actions will now only change when you set them to a new reference. This should cause a lit-html render using `this.action` to only dispatch the action the first time the reference is set. When you set this.action again, the new action should dispatch, even if the object is deeply equivalent. I think this is the desired behavior. Comment if you encounter any more issues with this.
